blog_site/blog/urls.py
from django.urls import path
from .views import post_list, post_detail, post_share, post_comment, post_search
from .feed import LatestPostFeed

app_name = "blog"

urlpatterns = [
    path("", post_list, name="post_list"),
    path("tag/<slug:tag_slug>/", post_list, name="post_list_with_tag"),
    # path("", PostListView.as_view(), name="post_list"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:slug>/",
        post_detail,
        name="post_detail",
    ),
    path("<int:post_id>/share/", post_share, name="post_share"),
    path("post/<int:post_id>/comment/", post_comment, name="post_comment"),
    path("feed/", LatestPostFeed(), name="post_feeds"),
    path("search/", post_search, name="post_search"),
]

blog_site/blog_site/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.urls import path, include

sitemaps = {"posts": PostSitemap}
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog_site/blog/models.py
from django.conf import settings
from django.utils import timezone
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="blog_posts"
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    body = models.TextField()
    photo = models.ImageField(upload_to="images/", default=" ", blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status, default=Status.DRAFT)
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug,
            ],
        )

    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=25)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created"]
        indexes = [models.Index(fields=["created"])]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog_site/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]


class SearchForm(forms.Form):
    query = forms.CharField()

blog_site/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger, InvalidPage
from django.views.generic import ListView
from django.core.mail import send_mail
from django.contrib.postgres.search import TrigramSimilarity
from django.db.models import Count
from django.views.decorators.http import require_POST

from taggit.models import Tag
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm


class PostListView(ListView):
    """An alternative to the post_list function based view"""

    queryset = Post.published.all()
    paginate_by = 3
    context_object_name = "posts"

    template_name = "blog/post/list.html"


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    paginator = Paginator(post_list, 3)
    page_number = request.GET.get("page", 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, "blog/post/list.html", {"posts": posts, "tag": tag})


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        publish__year=year,
        publish__month=month,
        publish__day=day,
        slug=slug,
    )
    form = CommentForm()
    comments = post.comments.filter(active=True)
    # Retrieving related posts by tags.
    post_tag_ids = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(tags__in=post_tag_ids).exclude(id=post.id)

    # Retrieving one post incase the same posts have the same tags, and also returning 4 posts by slicing.
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:4]
    # You can even use the similar_objects() method from taggit
    #  to retrieve the similar objects that have the same tag
    # similiar_objects = post.tags.similar_objects()
    return render(
        request,
        "blog/post/detail.html",
        {
            "post": post,
            "form": form,
            "comments": comments,
            "similar_posts": similar_posts,
        },
    )


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = (
                f"{cd['name']} ({cd['email']})" f" Recommends you read {post.title}"
            )
            message = (
                f"Read {post.title} at {post_url} \n\n"
                f"{cd['name']}'s comments: {cd['comment']}"
            )
            send_mail(
                subject=subject,
                message=message,
                from_email=None,
                recipient_list=[cd["to"]],
            )
            sent = True
    else:
        form = EmailPostForm()
    return render(
        request,
        "blog/post/share.html",
        {
            "post": post,
            "form": form,
            "sent": sent,
        },
    )


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(
        request,
        "blog/post/comment.html",
        {"post": post, "form": form, "comment": comment},
    )


# On 21st/May/2025 I was engaged with Building Tomorrow work, so I didn't code.
# On 23rd/May/2025 I was engaged with the donor visit (Building Tomorrow work) and I didn't code.
# On 24th/May/2025 I was engaged with the thanks giving ceremony of Madam Rhonah, and I didn't code.


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            results = (
                Post.published.annotate(similarity=TrigramSimilarity("body", query))
                .filter(similarity__gt=0.1)
                .order_by("-similarity")
            )

    return render(
        request,
        "blog/post/search.html",
        {"form": form, "query": query, "results": results},
    )

blog_site/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>
    <div id="content">

        {% block content %}

        {% endblock content %}

    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p><a href="{% url 'blog:post_search' %}">Search For Posts.</a></p>
        <p>Enjoy the content. We have so far written {% total_posts %} posts.</p>
        <p><a href="{% url 'blog:post_feeds' %}">Subscribe to my RSS feed.</a></p>
        <h3>Latest Posts.</h3>
        {% show_latest_posts 3 %}

        <h3>Most Commented Posts.</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
            <li><a href="{{post.get_absolute_url}}">{{post.title}}</a></li>
            {% endfor %}
        </ul>

    </div>
</body>

</html>

blog_site/blog/templates/blog/includes/comment_form.html
<h2>Add a new comment.</h2>

<form action="{% url 'blog:post_comment' post.id %}" method="post">
    {% csrf_token %}
    <div class="left">
        {{form.name.as_field_group}}
    </div>
    <div class="left">
        {{form.email.as_field_group}}
    </div>
    {{form.body.as_field_group}}

    <p><input type="submit" value="Add Comment"></p>
</form>



{% comment %}
<form action="{% url 'blog:post_comment' post.id %}" method="post">
    {% csrf_token %}
    {% for field in form %}
    {{field.errors}} {{field.label_tag}} {{field}}
    {% endfor %}
    <input type="submit" value="Add Comment">
</form>

{% endcomment %}

blog_site/blog/templates/blog/post/comment.html
{% extends 'blog/base.html' %}

{% block title %}Add a comment{% endblock title %}

{% block content %}

{% if comment %}
<h2>Your comment has been added.</h2>
<p><a href="{{post.get_absolute_url}}">Back to the post.</a></p>

{% else %}

{% include 'blog/includes/comment_form.html' %}

{% endif %}


{% endblock content %}

blog_site/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}{{post.title}}{% endblock title %}


{% block content %}
<h1><a href="{% url 'blog:post_list' %}">{{post.title}}</a></h1>
<img class="myimages" src="{{post.photo.url}}" alt="{{post.title}}">

<p class="date">Published {{post.publish}} by {{post.author}}</p>
{{post.body | markdown}}

<p><a href="{% url 'blog:post_share' post.id %}">Share this Post</a></p>
<h2>Similar posts.</h2>
{% for post in similar_posts %}
<p><a href="{{post.get_absolute_url}}">{{post.title}}</a></p>

{% empty %}
There are no similar posts yet.

{% endfor %}

{% with comments.count as total_comments %}
<h2>{{total_comments}} comment{{total_comments | pluralize}}</h2>
{% endwith %}

{% for comment in comments %}
<div class="comment">
    <p class="info">Comment {{forloop.counter}} by {{comment.name}} on {{comment.created}}</p>
    {{comment.body | linebreaks}}

</div>
{% empty %}
<p>There are no comments, be the first to comment.</p>


{% endfor %}

{% include 'blog/includes/comment_form.html' %}
{% endblock content %}

blog_site/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li><a href="{{post.get_absolute_url}}">{{post.title}}</a></li>
    {% endfor %}

</ul>

blog_site/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}My Blog{% endblock title %}


{% block content %}
<h1>My Blog</h1>

{% if tag %}
<h2>Posts with Tag: {{tag.name}} </h2>
{% endif %}


{% for post in posts %}
<h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>

<p class="tag">Tag:{% for tag in post.tags.all %}
    <a href="{% url 'blog:post_list_with_tag' tag.slug %}">{{tag.name}}</a>

    {% if not forloop.last %}
    ,
    {% endif %}

    {% endfor %}

</p>

<p class="date">{{post.publish}} by {{post.author}}</p>
{{post.body | markdown | truncatewords_html:10}}

{% endfor %}
{% include 'pagination.html' with page=posts %}
{% endblock content %}

blog_site/blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}

{% block title %}Search{% endblock title %}


{% block content %}

{% if query %}
<h1>Posts containing "{{query}}"</h1>

{% with results.count as total_results %}
<p>Found {{total_results}} result{{total_results | pluralize}}</p>
{% endwith %}

{% for post in results %}

<h1><a href="{{post.get_absolute_url}}">{{post.title}}</a></h1>
<p>{{post.body | truncatewords_html:12}}</p>

{% empty %}
<p>There are no results for your search.</p>

{% endfor %}

<p><a href="{% url 'blog:post_search' %}">Search again.</a></p>

{% else %}

<h1>Search For Posts.</h1>
<p><a href="{% url 'blog:post_list' %}">Back to posts.</a></p>
<form method="get">
    {{form.as_p}}
    <input type="submit" value="Search">

</form>
{% endif %}



{% endblock content %}

blog_site/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Share a Post{% endblock title %}


{% block content %}

{% if sent %}
<h1>Email successfully sent</h1>
<p> {{post.title}} was successfully shared to {{form.cleaned_data.to}}</p>
{% else %}
<h1>Share {{post.title}} by e-mail.</h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Send E-mail">
</form>
{% endif %}


{% endblock content %}

blog_site/blog/templates/pagination.html
<div class="pagination">
    <span>
        <span class="step-links">

            {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}">Previous</a>
            {% endif %}
        </span>

        <span class="current">
            Page {{page.number}} of {{page.paginator.num_pages}}
        </span>

        {% if page.has_next %}
        <a href="?page={{page.next_page_number}}">Next</a>
        {% endif %}



    </span>

</div>

blog_site/templates/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{post.title}}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

</head>

<body>
    <h1>{{post.title}}</h1>
    <p>{{post.body}}</p>
    <p><img class="bookcover" src="{{ post.photo.url }}"></p>
    <p>Post By: {{post.author}}</p>
</body>

</html>

blog_site/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{post.title}}</title>

    <link rel="stylesheet" href="{% static 'css/base.css' %}">

</head>

<body>
    <h1>Hello</h1>
    <ol>
        {% for post in posts %}
        <h1>
            <li>{{post.title}}</li>
        </h1>
        <p>{{post.slug}}</p>
        <p>Published on: {{post.publish}} By: {{post.author}} </p>

        {% endfor %}
    </ol>






</body>

</html>